default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: demoshop_development

test:
  <<: *default
  database: demoshop_test

production:
  <<: *default
  database: demoshop_production
  username: postgres
